#include "fabm_driver.h" 
 
   ! Register coefficients 
   call self%get_parameter(self%NCrMesoZoo, 'NCrMesoZoo', 'molN molC-1', 'N:C molar ratio in MES', default=0.21_rk) 
   call self%get_parameter(self%NCrMicroZoo, 'NCrMicroZoo', 'molN molC-1', 'N:C molar ratio in MIC (Anderson and Pondhaven, 2003)', default=0.18_rk) 
   call self%get_parameter(self%NCrBac, 'NCrBac', 'molN molC-1', 'N:C (Goldman) ratio in BAC (Anderson and Pondhaven, 2003)', default=0.196_rk) 
   call self%get_parameter(self%NCrNoctiluca, 'NCrNoctiluca', 'molN molC-1', 'N:C molar ratio in NOC (Nakamura, 1998, JPR)', default=0.21_rk) 
   call self%get_parameter(self%NCrGelatinous, 'NCrGelatinous', 'molN molC-1', 'N:C molar ratio in GEL', default=0.25_rk) 
   call self%get_parameter(self%SiNrDiatoms, 'SiNrDiatoms', 'molSi molN-1', 'Si:N ratio in DI (Aksnes et al. 1994)', default=0.83_rk) 

   ! Register state variables 
   call self%register_state_variable(self%id_cfl, 'CFL', 'mmol C m-3', 'Small flagellate biomass in carbon',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_nfl, 'NFL', 'mmol N m-3', 'Large flagellate biomass in nitrogen',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_cem, 'CEM', 'mmol C m-3', 'Small flagellate biomass in carbon',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_nem, 'NEM', 'mmol N m-3', 'Small flagellate biomass in nitrogen',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_cdi, 'CDI', 'mmol C m-3', 'Diatom biomass in carbon',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_ndi, 'NDI', 'mmol N m-3', 'Diatom biomass in nitrogen',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_mic, 'MIC', 'mmol C m-3', 'Microzooplakton biomass',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_mes, 'MES', 'mmol C m-3', 'Mesozooplakton biomass',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_bac, 'BAC', 'mmol C m-3', 'Bacterial biomass',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_dcl, 'DCL', 'mmol C m-3', 'Labile detritus concentration in carbon',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_dnl, 'DNL', 'mmol N m-3', 'Labile detritus concentration in nitrogen',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_dcs, 'DCS', 'mmol C m-3', 'Semi-labile detritus concentration in carbon',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_dns, 'DNS', 'mmol C m-3', 'Semi-labile detritus concentration in nitrogen',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_nos, 'NOS', 'mmol N m-3', 'Nitrate concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_nhs, 'NHS', 'mmol N m-3', 'Ammonium concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_sio, 'SIO', 'mmol Si m-3', 'Silicilic acid concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_dox, 'DOX', 'mmol O2 m-3', 'Dissolved oxygen concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_dic, 'DIC', 'mmol C m-3', 'Dissolved inorganic carbon concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_odu, 'ODU', 'mmol ODU m-3', 'Oxygen demand unit concentration',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_poc, 'POC', 'mmol C m-3', 'Particulate organic carbon concentration',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_pon, 'PON', 'mmol N m-3', 'Particulate organic nitrogen concentration',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_sid, 'SID', 'mmol Si m-3', 'Detrital silicate concentration',minimum=0.0e-7_rk, vertical_movement=self%2.0_rk) 
   call self%register_state_variable(self%id_agg, 'AGG', 'm-3', 'Aggregates',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_gel, 'GEL', 'mmol C m-3', 'Gelatinous omnivorous biomass',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_noc, 'NOC', 'mmol C m-3', 'Gelatinous carnivorous biomass',minimum=0.0e-7_rk)
   call self%register_state_variable(self%id_pho, 'PHO', 'mmol P m-3', 'Phosphorus',minimum=0.0e-7_rk)

   ! Register mass balance variables 
   ! Nitrogen balance 
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_nfl)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_ndi)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_nem)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_mes, scale_factor=self%NCrMesoZoo)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_mic, scale_factor=self%NCrMicroZoo)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_bac, scale_factor=self%NCrBAC)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_pon)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_dnl)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_dns)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_nos)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_nhs)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_noc, scale_factor=self%NCrNoctiluca)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen, self%id_gel, scale_factor=self%NCrGelatinous)
   ! Carbon balance 
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_cfl)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_cdi)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_cem)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_mes)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_mic)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_bac)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_poc)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_dcl)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_dcs)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_dic)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_noc)
   call self%add_to_aggregate_variable(standard_variables%total_carbon, self%id_gel)
   ! Silicium balance 
   call self%add_to_aggregate_variable(standard_variables%total_silicate, self%id_ndi, scale_factor=self%SiNrDiatoms)
   call self%add_to_aggregate_variable(standard_variables%total_silicate, self%id_sio)
   call self%add_to_aggregate_variable(standard_variables%total_silicate, self%id_sid)
   ! Phosphorus balance 
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_nfl, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_ndi, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_nem, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_mes, scale_factor=self%NCrMesoZoo*self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_mic, scale_factor=self%NCrMicroZoo*self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_bac, scale_factor=self%NCrBAC*self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_pon, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_dnl, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_dns, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_nos, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_nhs, scale_factor=self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_noc, scale_factor=self%NCrNoctiluca*self%Pnredfield)
   call self%add_to_aggregate_variable(standard_variables%total_phosphorus, self%id_gel, scale_factor=self%NCrGelatinous*self%Pnredfield)

    ! Register environmental dependencies 
   call self%register_dependency(self%id_temp, standard_variables%temperature) 
   call self%register_dependency(self%id_salt, standard_variables%practical_salinity) 
   call self%register_dependency(self%id_wind, standard_variables%wind_speed) 
   call self%register_dependency(self%id_taub, standard_variables%bottom_stress) 

   end subroutine initialize 


